config/routes.rb
Rails.application.routes.draw do

  post '/superheros', to: 'superheros#search'

  # get '/search', to: 'searches#search', as: 'search_page'

  # get '/superheros', to: 'superheros#result', as: 'results_page'

  resources :superheros 

  resources :users
  # get '/login', to: 'sessions#new', as: 'login'
  # post '/login', to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy', as: :logout 

  post '/users/:id', to: "appointments#new"

  resources :appointments 
  resources :sessions 

  post '/sessions/new', to: 'sessions#create'

  post '/superheros/:id', to: "appointments#new"
  resources :searches

  # get '/superheros/:id', to: 'users#client', as: 'client'
  # get '/users/:id', to: 'users#heroes', as 'hero'
  # get '/appointments/new', to: 'users#customer', as 'customer'
  # get '/appointments/new', to: 'users#customer', as 'customer'



  # get 'appointments/index'
  # get 'superheros/index'
  # get 'users/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end 

app/models/user.rb
class User < ApplicationRecord
    has_many :appointments
    has_many :superheros, through: :appointments 
    has_many :client_users, foreign_key: :customer_id, class_name: 'Hero'
    has_many :user_heros, through: :client_users
    has_many :provider_users, foreign_key: :hrs_id, class_name: 'Hero'
    has_many :customers, through: :provider_users
    has_many :appointments, through: :client_users
    has_many :appointments, through: :provider_users

    validates :username, presence: true 
    validates :username, uniqueness: true 
    validates :intelligence, :strength, :speed, :durability, :power, :combat, numericality: { less_than: 50 }

    has_secure_password

    def customer_appointments
        x = Appointment.all.select do |appt|
            appt.customer_id == self.id
        end
        y = x.sort do |appt1, appt2| 
            appt1.start_time_military <=> appt2.start_time_military
        end
        y
    end

    def hero_appointments
        x = Appointment.all.select do |appt|
            appt.hrs_id == self.id
        end
        y = x.sort do |appt1, appt2| 
            appt1.start_time_military <=> appt2.start_time_military
        end
        y
    end

    def hero_appointments_for_validation
        x = Appointment.all.select do |appt|
            appt.hrs_id == self.id
        end
    end



    def total_appointments
        self.customer_appointments + self.hero_appointments
    end

    def hours_booked
        hours_booked = []
        array_of_appointments = self.hero_appointments_for_validation
        # array_of_appointments.delete(self.hero_appointments_for_validation.last)
        array_of_appointments.each do |appointment|
            total_time = appointment.end_time_military - appointment.start_time_military
            index = 0 
            while index < total_time do 
                hours_booked << appointment.start_time_military + index
                index += 1
            end
        end
        hours_booked
    end

    def self.search(search)   
        if search
            names = User.where(name: search, is_hero: "true")
            if names.any?
                user = User.where(name: search, is_hero: "true")
            else 
                User.all.select do |us|
                    us.is_hero == true   
                end
            end
        else
            User.all.select do |us|
                us.is_hero == true   
            end
        end
    end

    def first_and_last_name
        "#{self.first_name} #{self.last_name}"
    end

    def welcome
        "#{self.name}'s Page"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :show]

    def index
      @users = User.search(params[:search])
    end

    def show
      @user = User.find(params[:id])
      @appointment = Appointment.new
      if session[:view_count]
        session[:view_count] = session[:view_count] + 1 
      else 
        session[:view_count] = 1
      end 
    end

    def new
      @user = User.new
    end

    def create
      user = User.create(user_params) 
      if user.valid?
        session[:user_id] = user.id
        if user.is_hero == false
          redirect_to user_path(user)
        else
          redirect_to edit_user_path(user)
        end
      else
        flash[:errors] = user.errors.full_messages
        redirect_to new_user_path
      end
    end

    def edit
      @user = User.find(params[:id]) 
      if @user == @current_user
        render :edit 
      else
        flash[:errors] = "#{@user.name} can only edit this profile page" 
        redirect_to user_path(@user)
      end
    end

    def update
      user = User.find(params[:id])
      user.update(user_params)
      if user.valid?
        session[:user_id] = user.id
        redirect_to user_path(user)
        else
          flash[:errors] = user.errors.full_messages
          redirect_to edit_user_path(user)
        end
    end

    def destroy

        user = User.find(params[:id])
        appt_total = []
        appt_cust = Appointment.where(customer_id: user.id)
        appt_hrs = Appointment.where(hrs_id: user.id)
        appt_total = appt_cust + appt_hrs
        appt_total.each do |appointment| 
          appointment.destroy
        end
        user.destroy
        redirect_to new_session_path
    end
    private
    def user_params
      params.require(:user).permit!
    end

    # def search_params
    #   params.require(:search).permit!
    # end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% if @user.is_hero %>
    <h1>Edit Your Hero</h1>
<% else %>
    <h1>Edit Your User</h1>
<% end %>

<% if flash[:errors] %>
  <h2><%= flash[:errors] %></h2>
<% end %>

<% if @user.is_hero == true && @user.intelligence == 0 && @user.strength == 0 && @user.durability %>
    <h2> Please Fill Out Your Hero Attributes at the Bottom of this Form:</h2>
    <h3> Note that Our Audit Team Includes Professor Charles Xavier </h3>
    <h3> Any False Claims about Your Abilities Will be Treated as Fraud </h3> 
    <%= image_tag("https://www.superherodb.com/pictures2/portraits/10/100/113.jpg") %>
<% end %>

<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br>
  <label>Password</label>
  <%= f.password_field :password %><br>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %><br>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %><br>
  <%= f.label :location %>
  <%= f.select :location, ["DC", "NY", "SF"] %><br>
  <label>Do you want a premium membership?</label>
  <%= f.select :is_premium, [["Yes", true], ["No", false]] %><br>
   <label>Are you signing up as a hero?</label>
   <%= f.select :is_hero, [["Yes", true], ["No", false]] %><br>

        
    <h2>For Heroes ONLY:</h2>    
    <p>If you're not a hero, skip to 'Update User' below.</p>
    <h2>Enter Hero Information Below:</h2> 
    <label>Hero Name</label>
    <%= f.text_field :name %><br>
    <h4>Hero Attritube Ratings:</h4>
    <%= f.label :intelligence %>
    <%= f.text_field :intelligence %><br>
    <div> <%= f.label :strength %>
    <%= f.text_field :strength %><br></div>    <%= f.label :speed %>
    <%= f.text_field :speed %><br>
    <%= f.label :durability %>
    <%= f.text_field :durability %><br>
    <%= f.label :power %>
    <%= f.text_field :power %><br>
    <%= f.label :combat %>
    <%= f.text_field :combat %><br>


    <label> Photo URL (optional) </label>
    <%= f.text_field :img_url %><br>
    <label>Do You have Good or Bad Intentions?</label>
    <%= f.select :alignment, ["Good", "Bad"] %><br>
 

    <label> Hourly Rate </label>
    <%= f.text_field :price %><br>
    <div>
    <%= f.submit %>
    </div> 
    
<% end %>

<div>
<%= button_to "Delete This User", user_path(@user), method: :delete %>
</div>


<br>
<br>
<br>
<br>
<br>
<br>
<br> 
<p></p>

app/views/users/index.html.erb
<h1>Search by Hero Name:</h1>

<%= form_tag(users_path, method: :get) do %>
<p> 
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag ("Search") %>
</p>
<% end %>

<h2><%= link_to "Search Heroes by Price", new_search_path %></h2>


<% if @users %>
    <h1>List of All Available Heroes:</h1>
    <% @users.each do |us| %>
        <%= link_to us.name, user_path(us) %><br> 
    <% end %> 
<% else %> 
    <h1>There are currently no Heroes listed.</h1>
    <%= link_to "Search Superheroes", superheros_path %>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1><br>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <%= error %>
    <% end %>
<% end %>

<%= form_for @user do |f| %>

  <%= f.label :username %><br>
  <%= f.text_field :username %><br><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br><br>

  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %><br><br>

  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %><br><br>

  <%= f.label :location %><br>
  <%= f.select :location, ["DC", "NY"] %><br><br>

  <label>Nickname/Hero Name:</label>
  <%= f.text_field :name %><br>
  <label>Do you want a premium membership?</label><br>
  <%= f.select :is_premium, [["Yes", true], ["No", false]] %><br><br>

   <label>Are you signing up as a hero?</label><br>
   <%= f.select :is_hero, [["Yes", true], ["No", false]] %><br><br><br>

  <%= f.submit %>

<% end %>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<p></p>

app/views/users/show.html.erb
<% if @user.is_hero == true %>
    <h1>Hero Page</h1>
<% else %>
    <h1>User Page</h1>
<% end %> 

<% if flash[:errors] %>
  <h2><%= flash[:errors] %></h2>
<% end %>


<h2>Username: <%= @user.username %></h2>
<% if @user.is_hero == false %>
    <h3>First Name: <%= @user.first_name %></h3>
    <h3>Last Name: <%= @user.last_name %></h3>
<else>
    <h3>Hero Name: <%= @user.name %></h3>
<% end %>
<h3>Location: <%= @user.location %></h3>

<% if @current_user.is_premium == false %>
    <% if session[:view_count] % 2 == 1 %>
    <iframe width="656" height="489" src="https://www.youtube.com/embed/WWaLxFIVX1s" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% else %>
    <iframe width="821" height="462" src="https://www.youtube.com/embed/bEb1SjidOlA" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% end %> 
<% end %>


<% if @user.is_hero == true %>
    <p></p>
    Hourly Rate: <%= @user.price %><br>

    <h2>Ability Ratings </h2>
        Intelligence: <%= @user.intelligence %><br>
        Strength: <%= @user.strength %><br>
        Speed: <%= @user.speed %><br>
        Durability: <%= @user.durability %><br>
        Power: <%= @user.power %><br>
        Combat: <%= @user.combat %><br>
       
        <% if @user.alignment == nil %>
            The Light Side or the Dark, this Hero is currently undecided.
        <% else %>
            This Hero is currently listed as a <%= @user.alignment %> hero.<br>
        <%end%>
<% end %>

<h4>If You are <%= @user.name %> Here is a <%= link_to 'Link to Edit Your Profile', edit_user_path(@user) %></h4>

<%if @user.is_hero == true %>
    <% if @user.hero_appointments.any? %>  
        <h2>List of booked appointments as a hero:</h2> 
        <% @user.hero_appointments.each do |appt| %>
            <% cust = User.find_by(id: appt.customer_id) %> 
                <p></p>From <%= appt.start_time %> <%= appt.start_ampm %> to <%= appt.end_time %> <%= appt.end_ampm %> - Location: <%= appt.location %><br>
                Client: <%= cust.first_name %> <%= cust.last_name %><br>
                Services Requested: <%= appt.description_of_service %><br>      
            <% end %>
    <% else %> 
        <h3>This user has yet to book any appointments as a hero.</h3> 
    <% end %>
<% end %>


<% if @user.customer_appointments.any? %>  
    <h2>List of booked appointments as a customer:</h2> 
    <% @user.customer_appointments.each do |appt| %>
        <% if Superhero.find_by(id: appt.superhero_id) %>  
            <% provider = Superhero.find_by(id: appt.superhero_id) %>  
        <% elsif User.find_by(id: appt.hrs_id) %> 
            <% provider = User.find_by(id: appt.hrs_id) %> 
        <% end %>
              <p></p>From <%= appt.start_time %> <%= appt.start_ampm %> to <%= appt.end_time %> <%= appt.end_ampm %> - Location: <%= appt.location %><br>
              Hero: <%= provider.name %><br>
              Services Requested: <%= appt.description_of_service %><br>
    <% end %>
<% else %> 
    <h3>This user has yet to book any appointments as a customer.</h3> 
<% end %>

<% if @user.is_hero == true %>
    <h2> Book an Appointment with <%= @user.name %></h2>

    <%= form_for @appointment do |f| %>
        <%= f.label :location %><br>
        <%= f.select :location, ["DC", "NY"] %><br>

        <%= f.label :start_time %><br>
        <%= f.select :start_time, [1,2,3,4,5,6,7,8,9,10,11,12] %>
        <%= f.select :start_ampm, ["AM", "PM"] %><br>

        <%= f.label :end_time %><br>
        <%= f.select :end_time, [1,2,3,4,5,6,7,8,9,10,11,12] %>
        <%= f.select :end_ampm, ["AM", "PM"] %><br>

        <%= f.label :description_of_service %>
        <%= f.select :description_of_service, ["Protection", "Entertainment", "Chores", "Travel", "Murder"] %>

        <%= f.hidden_field :customer_id, :value => @current_user.id %>
        <%= f.hidden_field :hrs_id, :value => @user.id %> 

        <%= f.submit %>

    <% end %> 

<% end %>

<p></p>
<% if @user.img_url != nil %>
<%= image_tag("#{@user.img_url}") %>
<% end %> 

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<p></p>