config/routes.rb
Rails.application.routes.draw do

  post '/superheros', to: 'superheros#search'

  # get '/search', to: 'searches#search', as: 'search_page'

  # get '/superheros', to: 'superheros#result', as: 'results_page'

  resources :superheros 

  resources :users
  # get '/login', to: 'sessions#new', as: 'login'
  # post '/login', to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy', as: :logout 

  post '/users/:id', to: "appointments#new"

  resources :appointments 
  resources :sessions 

  post '/sessions/new', to: 'sessions#create'

  post '/superheros/:id', to: "appointments#new"
  resources :searches

  # get '/superheros/:id', to: 'users#client', as: 'client'
  # get '/users/:id', to: 'users#heroes', as 'hero'
  # get '/appointments/new', to: 'users#customer', as 'customer'
  # get '/appointments/new', to: 'users#customer', as 'customer'



  # get 'appointments/index'
  # get 'superheros/index'
  # get 'users/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end 

app/models/superhero.rb
require 'net/http'
require 'open-uri'
require 'json'

class Superhero < ApplicationRecord
    has_many :appointments
    has_many :users, through: :appointments 

    def self.price(attributes)
        price = 0 
        attributes.each do |attribute|
            if attribute == 100
                price += 10000000
            elsif attribute >= 90
                price += 1000000
            elsif attribute >= 80
                price += 50000
            elsif attribute >= 70 
                price += 20000
            elsif attribute >= 60
                price += 7500
            elsif attribute >= 50
                price += 2000
            elsif attribute >= 25
                price += 100
            else
                price += 20
            end
        end
        price
    end

    def self.search_api(hero_name)
        name_array = hero_name.split(" ")
        name = name_array.join("_")
        info = URI.parse("https://superheroapi.com/api.php/10100168794062182/search/#{name}")
        response = Net::HTTP.get_response(info)
        api_hero_information = JSON.parse(response.body)
        super_search = [] 
        if api_hero_information["response"] == "success"
            price_attributes = []
            api_hero_information["results"].each do |hero_info|
                website_id = hero_info["id"].to_i
                if Superhero.find_by(website_id: website_id)
                    superhero = Superhero.find_by(website_id: website_id)
                    super_search << superhero
                else 
                    name = hero_info["name"]
                    intelligence = hero_info["powerstats"]["intelligence"].to_i
                    price_attributes << intelligence
                    strength = hero_info["powerstats"]["strength"].to_i
                    price_attributes << strength
                    speed = hero_info["powerstats"]["speed"].to_i
                    price_attributes << speed
                    durability = hero_info["powerstats"]["durability"].to_i
                    price_attributes << durability
                    power = hero_info["powerstats"]["power"].to_i
                    price_attributes << power
                    combat = hero_info["powerstats"]["combat"].to_i
                    price_attributes << combat
                    alignment = hero_info["biography"]["alignment"]
                    img_url = hero_info["image"]["url"]
                    price = Superhero.price(price_attributes)
                    alter_ego = hero_info["biography"]["aliases"][0]
                    if alignment == "bad"
                        price = price * 2
                    end
                    new_sup = Superhero.create(alter_ego: alter_ego, name: name, intelligence: intelligence, strength: strength, speed: speed, durability: durability, power: power, combat: combat, alignment: alignment, img_url: img_url, price: price, website_id: website_id)
                    super_search << new_sup
                end
            end 
        end
        super_search
    end

    def name_and_alter
        "#{self.name} - Alias: #{self.alter_ego}"
    end

    def superhero_appointments 
        x = Appointment.all.select do |appt|
            appt.superhero_id == self.id
        end
        y = x.sort do |appt1, appt2| 
            appt1.start_time_military <=> appt2.start_time_military
        end
        y
    end

    def hours_booked
        hours_booked = []
        array_of_appointments = self.superhero_appointments
        array_of_appointments.delete(self.superhero_appointments.last)
        array_of_appointments.each do |appointment|
            total_time = appointment.end_time_military - appointment.start_time_military
            index = 0 
            while index < total_time do 
                hours_booked << appointment.start_time_military + index
                index += 1
            end
        end
        hours_booked
    end

end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  # skip_before_action :authorized

  def index
    @superheros = Superhero.all 
  end

  def show
    @superhero = Superhero.find(params[:id]) 
    @appointment = Appointment.new 
    if session[:view_count]
      session[:view_count] = session[:view_count] + 1 
    else 
      session[:view_count] = 1
    end 
  end

  def search
    # byebug
    @found_superheros = Superhero.search_api(params[:search])
    @superheros = Superhero.all 
    @bad_search = 0 
    if @found_superheros == [] 
      @bad_search = 1
      render :index
    else  
      render :index 
    end
  end

  def result 
  end

private 

  def superhero_params
    params.require(:superhero).permit(:search)
  end

end

app/helpers/superheros_helper.rb
module SuperherosHelper
end

app/views/superheros/index.html.erb
<br>

<h1>Search by Superhero Name:</h1>

<%= form_tag superheros_path, method: :post do %>
<p> 
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search" %>
</p>
<% end %>

<% if @bad_search == 1 %>
    <h2>Your search did not return any results.</h2> 
    <h2>Please choose another Superhero.</h2> 
<% end %>

<% if @bad_search == 0 %>
    <h1>Here Are Your Search Results:</h1>
    <% @found_superheros.each do |superhero| %>
        <%= link_to superhero.name_and_alter, superhero_path(superhero) %><br>
    <% end %>
    <p></p>
        Youtube Search for: <%= link_to @found_superheros[0].name, "https://www.youtube.com/results?search_query=#{@found_superheros[0].name}"%>
<% end %>



<br>

<h1>List of Searched Superheroes:</h1>

<% @superheros.each do |superhero| %>
    <%= link_to superhero.name_and_alter, superhero_path(superhero) %><br>
<% end %>

<br>
<br>
<br>

app/views/superheros/result.html.erb
<h1>Here Are Your Search Results:</h1>

<% @found_superheros.each do |superhero| %>
    <%= link_to superhero.name_and_alter, superhero_path(superhero) %><br>
<% end %>

app/views/superheros/search.html.erb
<h1>Here Are Your Search Results:</h1>

<% @found_superheros.each do |superhero| %>
    
<%= link_to superhero.name_and_alter, superhero_path(superhero) %><br>

<% end %>

app/views/superheros/show.html.erb
<h1>Superhero Page</h1>

Name: <%= @superhero.name %><br>
Alias: <%= @superhero.alter_ego %><br>
Hourly Rate: <%= @superhero.price %><br>
<h3>Abilities: </h3>
Intelligence: <%= @superhero.intelligence %><br>
Strength: <%= @superhero.strength %><br>
Speed: <%= @superhero.speed %><br>
Durability: <%= @superhero.durability %><br>
Power: <%= @superhero.power %><br>
Combat: <%= @superhero.combat %><br>
This Superhero is currently listed as a <%= @superhero.alignment %> superhero.<br>
<p></p>
<% if flash[:errors] %>
    <h1> Invalid Entry: </h1>
    <% flash[:errors].each do |error| %>
        <h3> <%= error %> </h3>
    <% end %>
<% end %>

<% if @current_user.is_premium == false %>
    <% if session[:view_count] % 2 == 1 %>
    <iframe width="731" height="489" src="https://www.youtube.com/embed/8rwPovyR9HY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% else %>
    <iframe width="821" height="462" src="https://www.youtube.com/embed/UiyDmqO59QE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    <% end %> 
<% end %>

<% if @superhero.appointments.any? %>  
    <h2> This Superhero has Booked </h2>
    <% @superhero.superhero_appointments.each do |appt| %>
        <% cust = User.find_by(id: appt.customer_id) %> 
        
               <p></p>From <%= appt.start_time %> <%= appt.start_ampm %> to <%= appt.end_time %> <%= appt.end_ampm %> - Location: <%= appt.location %><br><br>
               Client: <%= cust.first_name %> <%= cust.last_name %><br>
               Services Requested: <%= appt.description_of_service %><br>
    <% end %>
<% else %> 
    <h2>This Superhero has yet to book any appointments.</h2>
<% end %> 

    <h2> Book an Appointment with <%= @superhero.name %></h2>
    <%= form_for @appointment do |f| %>
        <%= f.label :location %><br>
        <%= f.select :location, ["DC", "NY"] %><br>

        <%= f.label :start_time %><br>
        <%= f.select :start_time, [1,2,3,4,5,6,7,8,9,10,11,12] %>
        <%= f.select :start_ampm, ["AM", "PM"] %><br>

        <%= f.label :end_time %><br>
        <%= f.select :end_time, [1,2,3,4,5,6,7,8,9,10,11,12] %>
        <%= f.select :end_ampm, ["AM", "PM"] %><br>

        <%= f.label :description_of_service %><br>
        <%= f.select :description_of_service, ["Protection", "Entertainment", "Chores", "Travel", "Felonious Robbery"] %><br>

        <%= f.hidden_field :customer_id, :value => @current_user.id %>
        <%= f.hidden_field :superhero_id, :value => @superhero.id %> 

        <%= f.submit %>

    <% end %> 

    <%= image_tag("#{@superhero.img_url}") %>

    <br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br> 
<p></p>