config/routes.rb
Rails.application.routes.draw do

  post '/superheros', to: 'superheros#search'

  # get '/search', to: 'searches#search', as: 'search_page'

  # get '/superheros', to: 'superheros#result', as: 'results_page'

  resources :superheros 

  resources :users
  # get '/login', to: 'sessions#new', as: 'login'
  # post '/login', to: 'sessions#create'
  # delete '/logout', to: 'sessions#destroy', as: :logout 

  post '/users/:id', to: "appointments#new"

  resources :appointments 
  resources :sessions 

  post '/sessions/new', to: 'sessions#create'

  post '/superheros/:id', to: "appointments#new"
  resources :searches

  # get '/superheros/:id', to: 'users#client', as: 'client'
  # get '/users/:id', to: 'users#heroes', as 'hero'
  # get '/appointments/new', to: 'users#customer', as 'customer'
  # get '/appointments/new', to: 'users#customer', as 'customer'



  # get 'appointments/index'
  # get 'superheros/index'
  # get 'users/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Aim higher. SuperHire</title> 
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
    
    body {
      background-image: url("https://wallup.net/wp-content/uploads/2018/03/20/373404-The_Avengers-minimalism-blue.jpg");
      background-repeat: no-repeat;
      background-position: center;
      background-size: cover;
      margin-top: 0px;
      color: white;
      background-attachment: scroll;
    }

    ul {
      list-style-type: none;
    #   width: 100%
    #    left: 0;
    #   right: 0;
    #   overflow: hidden;
    #   background-color: dodgerblue;
    #   text-align: center;
    }
    
    li {
      float: left;
      border-right: 1px solid white;
    }

    .nav {
      position: relative;
      top: 0;
      display: flex;
      justify-content: center;
      width: 100%
      list-style-type: none;
      align-items: stretch;
    }

    li a {
      display: block;
      width: 135px;
      height: 25px;
      background-color: dodgerblue;
      color: white;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
    }

    li a:hover {
      background-color: dodgerblue;
    }

    <!-- .active { -->
      <!-- background-color: cornflowerblue; -->
    <!-- } -->

    .footer {
      background-color: dodgerblue;
      color: white;
      display: block;
      padding: 0px;
      border: 0px solid white;
      position: fixed;
      left: 0;
      right: 0;
      bottom: 0;
      width: 100%;
      text-align: center;
    }


    
  </style>

  </head>

  <body>


    <div class="nav">
      <ul>
        <!-- <a class="active" href='/superheros'>Home</a></li> -->
        <li class="n"><a href='/superheros'>Home</a></li>

        <!-- <li class="n"><a class="active" href='/search'>Search for Superheroes</a></li> -->
        <!-- <li class="n"><a href='/superheros'>Search for Superheroes</a></li> -->
        <li class="n"><%= link_to "Search Superheroes", superheros_path %></li>
        <li class="n"><a href='/users'>Search Heroes</a></li>
        <% if @current_user %>
          <li class="right"><%= link_to @current_user.welcome, user_path(@current_user) %></li>
          <li class="right"><%= link_to 'Logout', "/sessions/#{@current_user.id}", method: :delete %></li>
        <% else %>
          <li class="right"><%= link_to "Sign Up", new_user_path %></li>
          <li class="right"><%= link_to 'Login', new_session_path, method: :get %></li>
        <% end %>
      </ul>
    </div>

<%= yield %>

    <div class="footer">
      <h1>Aim higher. <i>SUPER</i> Hire.</h1>
    </div>
  </body>
</html>